version: "3"

services:
  nginx:
    image: nginx:1.23.2
    ports:
      - "80:80"
    volumes:
      - static_files:/code/drones_api/static
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      drones_subnet:
        aliases:
          - nginx
    restart: "on-failure"
  db:
    image: postgres:13.4
    restart: always
    container_name: drones_db
    networks:
      drones_subnet:
        aliases:
          - postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
  api:
    container_name: drones_api
    build: .
    volumes:
      - static_files:/code/drones_api/static/
      - ./data/media:/code/drones_api/media/
      - ./data/logs:/code/logs/
    env_file:
      - .env
    networks:
      drones_subnet:
        aliases:
          - drones_api
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

volumes:
  static_files:

networks:
  drones_subnet: