[tool.poetry]
name = "drones_api"
version = "0.1.0"
description = "Dron Transportation Infrastructure API"
authors = ["Reinier Hernández <sasuke.reinier@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
Django = "^3.2"
psycopg2 = "^2.9.5"

[tool.poetry.dev-dependencies]
coverage = "^6.5.0"
black = "^22.10.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
