# Generated by Django 3.2.16 on 2022-10-25 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0002_auto_20221025_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='drone_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='medications', to='drones.drone'),
        ),
    ]
