# Generated by Django 3.2.16 on 2022-10-27 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0003_alter_medication_drone_assigned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drone',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['id']},
        ),
    ]
