# Generated by Django 3.2.16 on 2022-10-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0004_auto_20221027_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='image',
            field=models.ImageField(upload_to='medications/'),
        ),
    ]
